
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sample.soap.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.sample.schema.sample.ProductRequestElement;
import com.sample.schema.sample.ProductResponseElement;
import com.sample.soap.webservice.Product;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-03T21:04:50.342-04:00
 * Generated source version: 3.3.6
 *
 */

@javax.jws.WebService(
                      serviceName = "ProductService",
                      portName = "Product",
                      targetNamespace = "http://sample.com/soap/webservice",
                      wsdlLocation = "classpath:sample.wsdl",
                      endpointInterface = "com.sample.soap.webservice.Product")

public class ProductImpl implements Product {

    private static final Logger LOG = Logger.getLogger(ProductImpl.class.getName());

    /* (non-Javadoc)
     * @see sample.com.soap.webservice.Product#getProduct(sample.com.schema.sample.ProductRequestElement request)*
     */
    public ProductResponseElement getProduct(ProductRequestElement request) {
        LOG.info("Executing operation getProduct");
        System.out.println(request);
        try {
        	System.out.println("Calling database..");
        	System.out.println("Getting object");
            ProductResponseElement _return = new ProductResponseElement();
            _return.setManufacturer("Apple");
            _return.setName("iWatch");
            _return.setPrice(321.99f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
